SELECT TOP 1000 
APPEALS.APAP_ID AS 'Appeals',
PREAUTHS.UMUM_REF_ID AS 'Pre-Auths'


FROM [DATABASE].[dbo].[CMC_APLK_APP_LINK] AS LINKS
LEFT JOIN [dbo].[CMC_APAP_APPEALS] AS APPEALS ON APPEALS.APAP_ID = LINKS.APAP_ID
LEFT JOIN [dbo].[CMC_UMSV_SERVICES] AS PREAUTHS ON PREAUTHS.UMUM_REF_ID = LINKS.APLK_ID
WHERE APPEALS.APAP_PRPR_ID1 = 'PROVIDER ID' OR APPEALS.APAP_PRPR_ID2 = 'PROVIDER ID' OR APPEALS.APAP_PRPR_ID3 = 'PROVIDER ID' 